name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
      placeholder: Describe the problem or limitation you're facing
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: How does the project currently handle this (if at all)?
      placeholder: |
        - Current behavior
        - Current limitations
    validations:
      required: false

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: Break down the implementation into tasks (if known)
      placeholder: |
        - [ ] Task 1
        - [ ] Task 2
    validations:
      required: false

  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: What should be the end result?
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any related files, links, documentation, or examples
    validations:
      required: false
