name: Task
description: A general task or chore (refactoring, maintenance, etc.)
title: "[Task]: "
labels: ["chore"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for maintenance tasks, refactoring, or other chores.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Why is this task needed?
      placeholder: Describe the motivation for this task
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: What is the current situation?
      placeholder: |
        - Current code/config state
        - Any issues or limitations
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: Break down the work into actionable items
      placeholder: |
        - [ ] Task 1
        - [ ] Task 2
    validations:
      required: true

  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: What should be the result when this is complete?
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any related files, documentation, or resources
    validations:
      required: false
